FROM golang:1.16-alpine

LABEL maintainer="jinlog<jinlong4696@163.com>"

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=https://goproxy.cn,https://goproxy.io,direct \
    ETCD_ENDPOINTS="127.0.0.1:2379" \
    ETCD_PASSWORD="" \
    NODE_NAME="" \
    BINLOGO_ENV="production" \
    CONSOLE_LISTEN="0.0.0.0" \
    CONSOLE_PORT="9999" \
    CLUSTER_NAME="cluster"

WORKDIR /binlogo


ADD . /binlogo

RUN go build /binlogo/cmd/server/binlogo.go

EXPOSE 9999

CMD ["/binlogo/server --configs /binlogo/configs/binlogo.yaml"]
