apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: binlogo
  name: binlogo
spec:
  sessionAffinity: None
  selector:
    app: binlogo
  ports:
    - name: console
      protocol: TCP
      port: 9999
      targetPort: 9999
  clusterIP: None
