apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: binlogo
  name: binlogo
  annotations:
    kubesphere.io/alias-name: binlogo
    kubesphere.io/serviceType: statefulservice
spec:
  sessionAffinity: None
  selector:
    app: binlogo
  ports:
    - name: console
      protocol: TCP
      port: 80
      targetPort: 9999
  clusterIP: None
