env: dev
cluster:
  name: cluster1
node:
  name: node3
console:
  port: 9955
  listen: 0.0.0.0
etcd:
  endpoints:
    - "localhost:12379"
store:
  type: etcd
  etcd:
    endpoints:
      - "localhost:12379"
