env: dev
cluster:
  name: cluster1
node:
  name: node2
console:
  port: 9900
  listen: 0.0.0.0
etcd:
  endpoints:
    - "localhost:12379"
store:
  type: etcd
  etcd:
    endpoints:
      - "localhost:12379"
