env: production
cluster:
  name: cluster1
  nodes:
    - 127.0.0.1:50001
    - 127.0.0.1:50002

# node configs. Different node should have different name.
node:
  name: node1
  port: 50001
# console configs
console:
  port: 9999
  listen: 0.0.0.0
# Etcd configs
etcd:
  endpoints:
    - "localhost:2379"
  password:
  username:
